spring.application.name=SpeechManagementAPI

server.port=8080

# DATABASE
spring.datasource.url=jdbc:h2:mem:speechmanagamentdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.h2.console.enabled=true

springdoc.swagger-ui.path=/api/speech/swagger-ui.html

